"""add review knowledge qa models

Revision ID: 18aa07f432ae
Revises: 059980b3fb14
Create Date: 2026-09-20 17:04:56.050707

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "18aa07f432ae"
down_revision: str | None = "059980b3fb14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kb_document",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("doc_type", sa.String(length=16), nullable=False),
        sa.Column("corpus_tier", sa.Integer(), server_default="1", nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("law_name", sa.String(length=200), nullable=True),
        sa.Column("article_no", sa.String(length=64), nullable=True),
        sa.Column("chapter_path", sa.String(length=300), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("abolished_date", sa.Date(), nullable=True),
        sa.Column("revision", sa.String(length=32), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("source_url", sa.String(length=512), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=True),
        sa.Column("index_status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("indexed_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True),
        sa.Column("deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kb_document")),
        sa.UniqueConstraint("content_hash", name="uk_kb_document_hash"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "risk_rule",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("rule_code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("risk_level", sa.String(length=8), nullable=False),
        sa.Column("condition_expr", sa.Text(), nullable=False),
        sa.Column("conclusion", sa.Text(), nullable=False),
        sa.Column("suggestion", sa.Text(), nullable=True),
        sa.Column("legal_basis", sa.Text(), nullable=True),
        sa.Column("match_keywords", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_rule")),
        sa.UniqueConstraint("rule_code", name="uk_risk_rule_code"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "kb_chunk",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "kb_document_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("chunk_no", sa.Integer(), nullable=False),
        sa.Column("chunk_type", sa.String(length=16), server_default="article", nullable=False),
        sa.Column("article_no", sa.String(length=64), nullable=True),
        sa.Column("law_name", sa.String(length=200), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("vector_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["kb_document_id"], ["kb_document.id"], name="fk_kb_chunk_document"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kb_chunk")),
        sa.UniqueConstraint("kb_document_id", "chunk_no", name="uk_kb_chunk_doc_no"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "qa_session",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("message_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "last_message_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True
        ),
        sa.Column("deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_qa_session_user"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qa_session")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "risk_rule_source",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "risk_rule_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "kb_document_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["kb_document_id"], ["kb_document.id"], name="fk_rule_source_doc"),
        sa.ForeignKeyConstraint(["risk_rule_id"], ["risk_rule.id"], name="fk_rule_source_rule"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_rule_source")),
        sa.UniqueConstraint("risk_rule_id", "kb_document_id", name="uk_risk_rule_source"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "qa_message",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "qa_session_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text().with_variant(mysql.MEDIUMTEXT(), "mysql"), nullable=False),
        sa.Column("has_citation", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=True),
        sa.Column("token_usage", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["qa_session_id"], ["qa_session.id"], name="fk_qa_message_session"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qa_message")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "qa_citation",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "qa_message_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "kb_document_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "kb_chunk_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("quoted_text", sa.Text(), nullable=True),
        sa.Column("relevance_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["kb_chunk_id"], ["kb_chunk.id"], name="fk_qa_citation_chunk"),
        sa.ForeignKeyConstraint(["kb_document_id"], ["kb_document.id"], name="fk_qa_citation_doc"),
        sa.ForeignKeyConstraint(["qa_message_id"], ["qa_message.id"], name="fk_qa_citation_message"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qa_citation")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "review_task",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "contract_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "contract_version_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "user_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column("progress", sa.Integer(), server_default="0", nullable=False),
        sa.Column("extracted_terms", sa.JSON().with_variant(mysql.JSON(), "mysql"), nullable=True),
        sa.Column("raw_llm_output", sa.JSON().with_variant(mysql.JSON(), "mysql"), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("started_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True),
        sa.Column("finished_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True),
        sa.Column("deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contract_id"], ["contract.id"], name="fk_review_task_contract"),
        sa.ForeignKeyConstraint(
            ["contract_version_id"], ["contract_version.id"], name="fk_review_task_version"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_review_task_user"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_task")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "review_report",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "review_task_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "file_object_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("format", sa.String(length=8), server_default="pdf", nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("high_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("medium_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("low_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["file_object_id"], ["file_object.id"], name="fk_review_report_file"),
        sa.ForeignKeyConstraint(["review_task_id"], ["review_task.id"], name="fk_review_report_task"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_report")),
        sa.UniqueConstraint("review_task_id", name="uk_review_report_task"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "risk_point",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "review_task_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("risk_level", sa.String(length=8), nullable=False),
        sa.Column("risk_category", sa.String(length=32), nullable=True),
        sa.Column("clause_title", sa.String(length=200), nullable=True),
        sa.Column("clause_text", sa.Text(), nullable=True),
        sa.Column("char_start", sa.Integer(), nullable=True),
        sa.Column("char_end", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("suggestion", sa.Text(), nullable=True),
        sa.Column("legal_basis", sa.Text(), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column(
            "kb_document_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "risk_rule_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("is_dismissed", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["kb_document_id"], ["kb_document.id"], name="fk_risk_point_kb_doc"),
        sa.ForeignKeyConstraint(["review_task_id"], ["review_task.id"], name="fk_risk_point_task"),
        sa.ForeignKeyConstraint(["risk_rule_id"], ["risk_rule.id"], name="fk_risk_point_rule"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_point")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_point")
    op.drop_table("review_report")
    op.drop_table("review_task")
    op.drop_table("qa_citation")
    op.drop_table("qa_message")
    op.drop_table("risk_rule_source")
    op.drop_table("qa_session")
    op.drop_table("kb_chunk")
    op.drop_table("risk_rule")
    op.drop_table("kb_document")
    # ### end Alembic commands ###
