"""p1 initial user file contract

Revision ID: 059980b3fb14
Revises:
Create Date: 2026-09-20 16:06:23.436770

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "059980b3fb14"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("account_type", sa.String(length=16), server_default="personal", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("last_login_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name="uk_user_email"),
        sa.UniqueConstraint("phone", name="uk_user_phone"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "contract",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "owner_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("contract_type", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("source", sa.String(length=16), server_default="upload", nullable=False),
        sa.Column(
            "current_version_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], name="fk_contract_owner"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "file_object",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_bucket", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=True),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column(
            "uploader_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["uploader_id"], ["user.id"], name="fk_file_object_uploader"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_object")),
        sa.UniqueConstraint("sha256", name="uk_file_object_sha256"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "user_profile",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("real_name", sa.String(length=64), nullable=True),
        sa.Column("org_name", sa.String(length=200), nullable=True),
        sa.Column("org_role", sa.String(length=64), nullable=True),
        sa.Column(
            "avatar_object_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_user_profile_user"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profile")),
        sa.UniqueConstraint("user_id", name="uk_user_profile_user"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "contract_version",
        sa.Column(
            "id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "contract_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column(
            "file_object_id",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("plain_text", sa.Text().with_variant(mysql.LONGTEXT(), "mysql"), nullable=True),
        sa.Column("text_source", sa.String(length=16), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_by",
            sa.BigInteger()
            .with_variant(mysql.BIGINT(unsigned=True), "mysql")
            .with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=3), "mysql"),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contract_id"], ["contract.id"], name="fk_contract_version_contract"),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], name="fk_contract_version_creator"),
        sa.ForeignKeyConstraint(["file_object_id"], ["file_object.id"], name="fk_contract_version_file"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract_version")),
        sa.UniqueConstraint("contract_id", "version_no", name="uk_contract_version"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###

    # 手工补充：contract 与 contract_version **互相引用**（循环外键），
    # 无法在建表语句里声明 —— 建第一张表时另一张还不存在。
    # 因此两张表都建好之后，再单独补这条约束。对应 04-数据库设计 §6.2。
    op.create_foreign_key(
        "fk_contract_current_version",
        "contract",
        "contract_version",
        ["current_version_id"],
        ["id"],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_contract_current_version", "contract", type_="foreignkey")
    op.drop_table("contract_version")
    op.drop_table("user_profile")
    op.drop_table("file_object")
    op.drop_table("contract")
    op.drop_table("user")
    # ### end Alembic commands ###
